project_name: scratchdata

dist: .builds
env:
  - CGO_ENABLED=1

builds:
# linux amd64
  - id: scratchdata-linux-amd64
    binary: scratchdata
    main: ./
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-lc -lrt -lpthread --static"

# # windows amd64
#   - id: scratchdata-windows-amd64
#     binary: scratchdata
#     main: ./
#     env:
#       - CC=x86_64-w64-mingw32-gcc
#       - CXX=x86_64-w64-mingw32-g++
#     goos:
#       - windows
#     goarch:
#       - amd64
#     flags:
#       - -trimpath
#       - -buildmode=exe

# darwin arm64
  - id: scratchdata-darwin-arm64
    binary: scratchdata
    main: ./
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -trimpath

# darwin amd64
  - id: scratchdata-darwin-amd64
    binary: scratchdata
    main: ./
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -trimpath

archives:
  - id: scratchdata
    builds:
      - scratchdata-linux-amd64
      # - scratchdata-windows-amd64
      - scratchdata-darwin-arm64
      - scratchdata-darwin-amd64
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    # files:
    #   - LICENSE
    #   - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc