# .github/workflows/release.yml
name: goreleaser

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      # More assembly might be required: Docker logins, GPG, etc.
      # It all depends on your needs.

      - name: Cache osx-cross
        uses: actions/cache@v2
        with:
          path: /home/runner/work/_actions/mbround18/setup-osxcross/v1/osxcross/target/bin
          key: osxcross
          restore-keys: |
            osxcross

      - name: Check if osx-cross is cached
        id: osx-cross-hit
        run: |
          echo "cache-hit=$(test -d /home/runner/work/_actions/mbround18/setup-osxcross/v1/osxcross/target/bin && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Install osx-cross
        if: steps.osx-cross-hit.outputs.cache-hit != 'true'
        uses: mbround18/setup-osxcross@v1
        with:
          osx-version: "12.3"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: dist/*