# .github/workflows/release.yml
name: goreleaser

on:
  pull_request:
  push:
    # run only against tags
    # tags:
    #   - "*"

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  goreleaser-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser for Linux
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean --config ./scripts/.goreleaser-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: dist/*

  goreleaser-darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser for Darwin
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config ./scripts/.goreleaser-darwin.yml
          workdir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: dist/*